### ISSUE TITLE
openni2.launch error

### ISSUE THREAD

**Issue by woshidag** [percipioxyz/camport_ros#1]
when i use "roslaunch openni2_launch openni2.launch", there are some error.
but do not influence the result of use(不影响正常使用-_-）.

[ INFO] [1470988614.408921551]: Device "1" found.
PercipioDriver::deviceOpen, uri = 1
   141969 VERBOSE    no processor for this packet
   144500 VERBOSE    deviceparam packet accepted
   144525 INFO       waiting device...
   144536 VERBOSE    no processor for this packet
   144740 VERBOSE    no processor for this packet
   154443 VERBOSE    deviceparam packet accepted
   154485 INFO       no custom config data
   154500 VERBOSE    no processor for this packet
   154751 VERBOSE    no processor for this packet
   164461 VERBOSE    deviceparam packet accepted
   164522 VERBOSE    no processor for this packet
   164979 VERBOSE    no processor for this packet
   174455 VERBOSE    deviceparam packet accepted
   174526 VERBOSE    no processor for this packet
   174805 VERBOSE    no processor for this packet
   184428 VERBOSE    deviceparam packet accepted
PercipioDriver: success to open device!
   184487 VERBOSE    no processor for this packet
   184825 VERBOSE    no processor for this packet
[ERROR] [1470988614.493288397]: Unsupported IR video mode - Resolution: 640x480@30Hz Format: Gray16
[ERROR] [1470988614.493372955]: Unsupported color video mode - Resolution: 640x480@30Hz Format: RGB888
DEBUG: PercipioDevice::createStream
DEBUG: PercipioDevice::createStream, return pImage 0x1fbd520

**Comment by percipioxyz** [comment]
当前发布的这款模组不支持color和IR图像模式，出现这个提示是正常的。

**Comment by woshidag** [comment]
好的，谢谢
