### ISSUE TITLE
No matching device found.... 

### ISSUE THREAD

**Issue by gbdpf** [percipioxyz/camport_ros#2]
My device is DS462, the problem is:

[ INFO] [1541856553.614585027]: No matching device found.... waiting for devices. Reason: std::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /home/dpf/workspace/camport_ros-master/src/openni2_camera/src/openni2_driver.cpp @ 716 : Invalid device number 11, there are 0 devices connected.

   Hope your help

**Comment by towersla** [comment]
install camport3_openni2/binary
sudo dpkg -i libopenni2-0_2.2.0.33+dfsg-4_amd64.deb
sudo dpkg -i libopenni2-dev_2.2.0.33+dfsg-4_amd64.deb
