### ISSUE TITLE
‘ONI_DEVICE_PROPERTY_CALIB_INTRISTIC’ was not declared in this scope

### ISSUE THREAD

**Issue by idarren-deng** [percipioxyz/camport_ros#3]
camport_ros/openni2_camera/src/openni2_device.cpp:664:55: error: ‘ONI_DEVICE_PROPERTY_CALIB_INTRISTIC’ was not declared in this scope
  if (openni::STATUS_OK != openni_device_->getProperty(ONI_DEVICE_PROPERTY_CALIB_INTRISTIC, (void*)data, size))

**Comment by longbowliu** [comment]
did you fixed it , plz  let me know. tks!

**Comment by bartfj** [comment]
> camport_ros/openni2_camera/src/openni2_device.cpp:664:55: error: ‘ONI_DEVICE_PROPERTY_CALIB_INTRISTIC’ was not declared in this scope
> if (openni::STATUS_OK != openni_device_->getProperty(ONI_DEVICE_PROPERTY_CALIB_INTRISTIC, (void*)data, size))

Do you install camport openni2?
