### ISSUE TITLE
catkin_make error under ubuntu18.04 ros melodic

### ISSUE THREAD

**Issue by gongyue666** [percipioxyz/camport_ros#4]
change to :
DepthImageToLaserScanNodelet.cpp:
PLUGINLIB_EXPORT_CLASS(depthimage_to_laserscan::DepthImageToLaserScanNodelet, nodelet::Nodelet)
openni2_camera_nodelet.cpp:
PLUGINLIB_EXPORT_CLASS(openni2_camera::OpenNI2DriverNodelet, nodelet::Nodelet)

**Comment by percipioxyz** [comment]
try Ros2
