### ISSUE TITLE
 Camera calibration file /home/usr_name/.ros/camera_info/rgb_PercipioDepth_Percipio.yaml not found.

### ISSUE THREAD

**Issue by debugAllTheTime** [percipioxyz/camport_ros#6]
当我启动ros读取/camera/depth_registered/points节点的时候
并不能得到彩色点云
并且显示
[ INFO] [1589593395.256986780]: camera calibration URL: file:///home/ysj/.ros/camera_info/rgb_PercipioDepth_Percipio.yaml
[ INFO] [1589593395.257291666]: Unable to open camera calibration file [/home/ysj/.ros/camera_info/rgb_PercipioDepth_Percipio.yaml]
[ WARN] [1589593395.257428151]: Camera calibration file /home/ysj/.ros/camera_info/rgb_PercipioDepth_Percipio.yaml not found.
请问这个怎么解决呢

**Comment by StanleyYake** [comment]
利用ROS这里，做RGB和深度相机的标定：[https://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration](url) ， 然后像Kinect那样，在~/.ros/camera_info/创建一个名为rgb_PercipioDepth_Percipio.yaml的文件放入自己的标定参数。

`image_width: 640
image_height: 480
camera_name: rgb_PercipioDepth_Percipio
camera_matrix:
  rows: 3
  cols: 3
  data: [722.627165, 0.000000, 332.128112, 0.000000, 724.938942, 250.738683, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.022072, -0.107713, 0.002095, -0.001196, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [512.812622, 0, 304.954281, 0, 0, 516.901001, 229.223571, 0, 0, 0, 1, 0]`

但是，我发现图漾的格式和Kinect的不一样，它不认。所以这里还得官方的人解答一下
![Screenshot from 2021-06-24 10-41-14](https://user-images.githubusercontent.com/7522853/123194255-c2bb2080-d4d8-11eb-9052-8a2ec79da0a3.png)

**Comment by luojianbin2006** [comment]
my env: ubuntu16.04, Ros kinetic
Make sure the version of  camport3 SDK and camport3 Openni2 is matched. For me, I install the  version of v1.5.15.
