### ISSUE TITLE
Failed to percipio projection file, /etc/openni2/percipio_registration.txt

### ISSUE THREAD

**Issue by StanleyYake** [percipioxyz/camport_ros#7]
Hello there, my camera is FM810, and use it in ROS kinetic, when I run ``roslaunch openni2_launch openni2.launch `, the rgb and depth image is OK, but when I want rgb cloud and run
`roslaunch openni2_launch openni2.launch depth_registration:=true` the RGB cloud is freeze and the console print "Failed to percipio projection file, /etc/openni2/percipio_registration.txt" what context should I put in this file. Could you kindly provide an example, thank in advance!

**Comment by percipioxyz** [comment]
fixed
