### ISSUE TITLE
error: narrowing conversion of ‘TY_PIXEL_FORMAT_TOF_IR_MONO16’ from ‘uint32_t’ {aka ‘unsigned int’} to ‘int’ [-Wnarrowing]

### ISSUE THREAD

**Issue by zhukeyi-stan** [percipioxyz/camport_ros#8]
When I try to build this project in my ROS Noetic, it reports this issue:

In file included from .../src/camport_ros/src/percipio_camera/src/percipio_interface.cpp:9:
.../src/camport_ros/src/percipio_camera/include/percipio_camera/image_process.hpp: In static member function ‘static int ImgProc::cvtColor(percipio::VideoFrameData&, percipio::VideoFrameData&)’:
.../src/camport_ros/src/percipio_camera/include/percipio_camera/image_process.hpp:587:14: error: narrowing conversion of ‘TY_PIXEL_FORMAT_TOF_IR_MONO16’ from ‘uint32_t’ {aka ‘unsigned int’} to ‘int’ [-Wnarrowing]
  587 |         case TY_PIXEL_FORMAT_TOF_IR_MONO16: {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Looks like the issue is because TY_PIXEL_FORMAT_TOF_IR_MONO16=2751463424(=0xa400,0000) which exceeds the range of the int  [-2147483648, 2147483647]. And the switch() only takes int.

It's a very strange error. I can fix this error by changing switch to if...else. But I am wondering if there're another ways to solve this problem.

My C++ Standard is 11.

**Comment by Jet-Zou** [comment]
tag:v3.6.45.3 （commit id: f52e1bd5076393976fa16b50d57e4d522be35b75）has fixed the g++-11 compilation error.
